# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FK7VUEgbEbvmba4AmkxWc2X30R6frKjB
"""

import pandas as pd

df = pd.read_csv("SpotifyFeatures.csv")
df.head()

df.isnull().sum()

df = df.dropna()

features = df[['danceability','energy','tempo','loudness','valence']]

df['energy_level'] = pd.cut(df['energy'],
                           bins=[0,0.3,0.6,1],
                           labels=['Low','Medium','High'])

df['tempo_category'] = pd.cut(df['tempo'],
                              bins=[0,90,120,200],
                              labels=['Slow','Medium','Fast'])

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(df['danceability'])
plt.title("Danceability Distribution")

sns.heatmap(features.corr(), annot=True)

sns.scatterplot(x='energy', y='danceability', data=df)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(features)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)

clusters = kmeans.fit_predict(X_scaled)

df['Cluster'] = clusters

from sklearn.decomposition import PCA

pca = PCA(n_components=2)

pca_result = pca.fit_transform(X_scaled)

df['PCA1'] = pca_result[:,0]
df['PCA2'] = pca_result[:,1]

plt.scatter(df['PCA1'], df['PCA2'], c=df['Cluster'])
plt.title("Spotify Song Clusters (PCA)")
plt.show()

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=42)

tsne_result = tsne.fit_transform(X_scaled)

df['TSNE1'] = tsne_result[:,0]
df['TSNE2'] = tsne_result[:,1]

plt.scatter(df['TSNE1'], df['TSNE2'], c=df['Cluster'])
plt.title("Spotify Song Clusters (t-SNE)")
plt.show()

df.groupby('Cluster')[features.columns].mean()

inertia = []

for k in range(1,10):
    kmeans = KMeans(n_clusters=k)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []

for k in range(1,10):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.plot(range(1,10), inertia, marker='o')
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

from sklearn.metrics import silhouette_score

score = silhouette_score(X_scaled, clusters)

print("Silhouette Score:", score)

def recommend(song_name):

    cluster = df[df['track_name']==song_name]['Cluster'].values[0]

    recommendations = df[df['Cluster']==cluster]['track_name'].head(10)

    return recommendations

import pandas as pd

# Save the clustered DataFrame to a CSV file
df.to_csv("spotify_tracks_clustered.csv", index=False)



